# Generated by Django 3.1.4 on 2021-01-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
