version: '3.7'

services:
      nginx:
        image: nginx:alpine
        ports:
        - 80:80
        # directorios para el archivo de configuración y archivos del static
        volumes:
        - ./conf:/etc/nginx/conf.d
        - ./web/static:/var/www/static 
        depends_on:
        - web
      web:
        build: .
        restart: always
        command: gunicorn mi_sitio_web.wsgi:application --bind 0.0.0.0:8000
        # command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - ./web:/web
      db:
        image: postgres
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
